import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
//import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="grid">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid__main magenta">
        <h1>This is a title</h1>
        <p>this is the main</p>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius eos
          itaque, sapiente in dolorem voluptatum libero odit facilis officiis a
          voluptates nulla ad quam esse labore repellat reiciendis, quae
          delectus.
        </p>
      </main>

      <aside className="grid__sidebar">
        <div className="grid__widget green">
          <h2>This is a title</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi,
            facere! Consequuntur, est vero nisi ducimus facilis animi molestiae
            similique recusandae tenetur deserunt fugit ipsum odit dicta
            dolores. Sint, ab laudantium!
          </p>
        </div>

        <div className="grid__widget magenta">
          <h2>Check out this cool thing!</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi,
            facere! Consequuntur, est vero nisi ducimus facilis animi molestiae
            similique recusandae tenetur
          </p>
        </div>

        <div className="grid__widget magenta">
          <h2>More cool thing is right here too!</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi, ipsa!
            Nulla, qui? Quidem non perspiciatis qui impedit quia?
          </p>
        </div>
      </aside>
    </div>
  );
};

export default Home;
